name: Build Web App
 
on:
  workflow_dispatch:
  push:
    branches: 
    - master
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore AspnetDemo/AspnetDemo.sln
 
    - name: Build and Publish Web App
      run: msbuild AspnetDemo/AspnetDemo.sln /p:Configuration=Release /p:DeployOnBuild=true /p:OutDir=output
 
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: webnargithub
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: AspnetDemo/output/_PublishedWebsites/AspnetDemo
